export const linkIconInstaBlack = "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/black-instagram-icon.png"
export const linkIconEmailBlack = "https://uxwing.com/wp-content/themes/uxwing/download/communication-chat-call/envelope-line-icon.png"
export const linkIconTelBlack = "https://uxwing.com/wp-content/themes/uxwing/download/communication-chat-call/ringing-phone-outline-icon.png"
export const linkIconLinkedin = "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/linkedin-app-icon.png"
export const linkIconLinkedinBlack = "https://img.icons8.com/?size=100&id=8808&format=png&color=1A1A1A"
export const linkIconWppBlack = "https://img.icons8.com/?size=100&id=TRtiP3z8pXb0&format=png&color=000000"
export const linkIconGithubBlack = "https://img.icons8.com/?size=100&id=62856&format=png&color=000000"

export const linkWpp = "https://wa.me/55081997347970"
export const linkGithub = "https://github.com/mathhen1"
export const linkLinkedin = "https://www.linkedin.com/in/matheus-henrique-609083271/"
export const linkInsta = "https://www.instagram.com/theteuzz"
export const linkMailTo = "mailto:mathen.dev.z@gmail.com?subject=Vim%20pelo%20site&body=Ol%C3%A1%2C%20gostaria%20de%20um%20servi%C3%A7o."